# Generated by Django 3.2.4 on 2021-06-18 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('representante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacao.beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_transacao', models.DateField()),
                ('hora_transacao', models.TimeField()),
                ('cartao', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('D', 'Debito'), ('C', 'Credito'), ('B', 'Boleto'), ('F', 'Financiamento'), ('RE', 'Recebimento Empréstimo'), ('V', 'Vendas'), ('RT', 'Recebimento TED'), ('RD', 'Recebimento DOC'), ('A', 'Aluguel')], max_length=2)),
                ('loja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacao.loja')),
            ],
        ),
    ]
