# Generated by Django 3.2.4 on 2021-06-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0002_movimento_saldo_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='representante_id',
        ),
        migrations.AddField(
            model_name='loja',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='representante',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Beneficiario',
        ),
    ]
